BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "E_IDENTIFICACAO" (
	"ID_IDENTIFICACAO"	INTEGER NOT NULL,
	"DATA_HORA"	NUMERIC NOT NULL,
	"LATITUDE"	NUMERIC NOT NULL,
	"LONGITUDE"	NUMERIC NOT NULL,
	"PLACA_VIRTUAL"	TEXT NOT NULL,
	"TRECHO"	TEXT NOT NULL,
	"POSICAO"	NUMERIC NOT NULL,
	PRIMARY KEY("ID_IDENTIFICACAO" AUTOINCREMENT),
	FOREIGN KEY("ID_IDENTIFICACAO") REFERENCES "OCORRENCIAS_PICO1"("ID_OCORRENCIA"),
	FOREIGN KEY("ID_IDENTIFICACAO") REFERENCES "E_OCORRENCIAS_CHOQUE1"("ID_OCORRENCIA"),
	FOREIGN KEY("ID_IDENTIFICACAO") REFERENCES "E_OCORRENCIAS_CHOQUE2"("ID_OCORRENCIA")
);
CREATE TABLE IF NOT EXISTS "E_OCORRENCIAS_CHOQUE1" (
	"ID_OCORRENCIA"	INTEGER NOT NULL,
	"PEG_PSI"	NUMERIC NOT NULL,
	"ACT"	NUMERIC NOT NULL,
	"F_MAX"	NUMERIC NOT NULL,
	PRIMARY KEY("ID_OCORRENCIA")
);
CREATE TABLE IF NOT EXISTS "E_OCORRENCIAS_CHOQUE2" (
	"ID_OCORRENCIA"	INTEGER NOT NULL,
	"PEG_PSI"	NUMERIC NOT NULL,
	"ACT"	NUMERIC NOT NULL,
	"F_MAX"	NUMERIC NOT NULL,
	PRIMARY KEY("ID_OCORRENCIA")
);
CREATE TABLE IF NOT EXISTS "OCORRENCIAS_PICO1" (
	"ID_OCORRENCIA"	INTEGER NOT NULL,
	"PEG_PSI"	NUMERIC NOT NULL,
	"ACT"	NUMERIC NOT NULL,
	"F_MAX"	NUMERIC NOT NULL,
	"ENGATE"	NUMERIC NOT NULL,
	"DELTA_T"	NUMERIC NOT NULL,
	PRIMARY KEY("ID_OCORRENCIA")
);
CREATE TABLE IF NOT EXISTS "F_IDENTIFICACAO" (
	"ID_IDENTIFICACAO"	INTEGER NOT NULL,
	"DATA_HORA"	NUMERIC NOT NULL,
	"LATITUDE"	NUMERIC NOT NULL,
	"LONGITUDE"	NUMERIC NOT NULL,
	"PLACA_VIRTUAL"	TEXT NOT NULL,
	"TRECHO"	TEXT NOT NULL,
	"POSICAO"	NUMERIC NOT NULL,
	PRIMARY KEY("ID_IDENTIFICACAO" AUTOINCREMENT),
	FOREIGN KEY("ID_IDENTIFICACAO") REFERENCES "F_OCORRENCIAS_2"("ID_OCORRENCIA"),
	FOREIGN KEY("ID_IDENTIFICACAO") REFERENCES "F_OCORRENCIAS_CHOQUE1"("ID_OCORRENCIA"),
	FOREIGN KEY("ID_IDENTIFICACAO") REFERENCES "OCORRENCIAS_PICO2"("ID_OCORRENCIA")
);
CREATE TABLE IF NOT EXISTS "F_OCORRENCIAS_CHOQUE1" (
	"ID_OCORRENCIA"	INTEGER NOT NULL,
	"PEG_PSI"	NUMERIC NOT NULL,
	"ACT"	NUMERIC NOT NULL,
	"F_MAX"	NUMERIC NOT NULL,
	PRIMARY KEY("ID_OCORRENCIA")
);
CREATE TABLE IF NOT EXISTS "F_OCORRENCIAS_CHOQUE2" (
	"ID_OCORRENCIA"	INTEGER NOT NULL,
	"PEG_PSI"	NUMERIC NOT NULL,
	"ACT"	NUMERIC NOT NULL,
	"F_MAX"	NUMERIC NOT NULL,
	PRIMARY KEY("ID_OCORRENCIA")
);
CREATE TABLE IF NOT EXISTS "OCORRENCIAS_PICO2" (
	"ID_OCORRENCIA"	INTEGER NOT NULL,
	"PEG_PSI"	NUMERIC NOT NULL,
	"ACT"	NUMERIC NOT NULL,
	"F_MAX"	NUMERIC NOT NULL,
	"ENGATE"	NUMERIC NOT NULL,
	"DELTA_T"	NUMERIC NOT NULL,
	PRIMARY KEY("ID_OCORRENCIA")
);
CREATE TABLE IF NOT EXISTS "FAVORITOS" (
	"ID_FAV"	INTEGER NOT NULL,
	"FAVORITO"	TEXT NOT NULL,
	PRIMARY KEY("ID_FAV" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "USERS" (
	"ID_USER"	INTEGER NOT NULL,
	"EMAIL"	TEXT NOT NULL,
	"SENHA"	TEXT NOT NULL,
	PRIMARY KEY("ID_USER"),
	FOREIGN KEY("ID_USER") REFERENCES "FAVORITOS"("ID_FAV")
);
COMMIT;
